services:
  db:
    image: postgres:18-alpine
    container_name: dipbot-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: dipbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local_password
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
